### ISSUE TITLE
Missing documentation for fluid form. select view helper

### ISSUE THREAD

**Issue by Eshelion** [FluidTYPO3/fluidtypo3org#42]
Right now for every version except 7.5.0 there is no documentation about view helper mentioned in title. Only 

> This view helper generates a [select]

is displayed.

**Comment by NamelessCoder** [comment]
This problem gets reported about once a month. There is nothing we can do about this; the un-quoted HTML piece exists in the XSD files and stem from the PHP class documentation. It has since been fixed (a long, long time ago) but the XSD files for older versions still contain, and still get regenerated with, this incorrectly formatted comment. It would be the same no matter which system generated the docs.

View the docs for a more recent version - the API hasn't changed that much and it behaves almost exactly the same.

**Comment by Eshelion** [comment]
The problem is, not only older version are broken - newer than 7.5.0 also don't have proper documentation. It isn't biggest problem or bug, as we can always look into code, but then, why even bother keeping these docs?

**Comment by NamelessCoder** [comment]
I don't mean to sound arrogant about this, but one broken VH documentation doesn't make the other ~250 working VH docs useless. You don't just discard an otherwise well-working docs rendering because of a ~0.4% error rate.

Hopefully you understand the core of the issue: the very source of the documentation, the XSD files that are *not authored by us*, contain an un-quoted, un-closed opening `<select>` tag - which is wrong in RST, Markdown and HTML alike. We did not write this so you really shouldn't blame us for it - or expect us to retroactively solve this for all TYPO3 versions up until the current one. Everything is affected by this, from our docs rendering to the official TYPO3 docs rendering to the IDE insights you get when mapping the XSD to a namespace.

**Comment by Eshelion** [comment]
Yeah, I understand the source of problem, I've just pointed, that it isn't problem only with older versions. I've reported problem here, cause people on irc channel told me to do so. My rhetorical question in earlier message came from assumption (which appears to be false), that you are also authors (or part of your team is) of said view helpers, so it is in your grasp to fix those bugs. I guess I should report this bug to authors of vhs then, shouldn't I? Or somebody else is author of those XSD files?

**Comment by NamelessCoder** [comment]
This particular VH is part of TYPO3 itself so you would have to report it to the TYPO3 core bug tracker. VHS isn't related here at all.

To clarify, the PHP class contains the markup that ends up in the XSD file and fixing the problem has to be done from the PHP class itself. TYPO3 does not ship XSD files, nor does it ship the utility that creates the XSD file - and the problem is not one that gets solved by editing an XSD file or making a change to the XSD generator (it assumes the PHP class is well formed and refrains from implementing fixes for edge case markup errors, not least because it is *markup agnostic* which is evident from VHS using Markdown and core classes using RST).

I have to be honest though: you should not expect this to be fixed since doing so isn't possible without making new patches for TYPO3 versions that are no longer supported and even with that, would not be possible to fix for any but the most recent bugfix release of those versions, which would again require new releases of completely discontinued TYPO3 versions.

I personally wouldn't spend time trying to achieve this - objectively speaking it has almost zero chance of being corrected because correcting it means departing from nearly all decisions made about release schedules and maintenance time frames.

I hate to say this, but I think this is one of those things you just have to live with. What's done is done in those TYPO3 versions where this is broken, just like with any other bug those TYPO3 versions might contain.

**Comment by Eshelion** [comment]
Right, it's core fluid, not VHS, I don't know why I wrote about VHS... Fixing this for master would be sufficient enough, as you've said, nobody would like to resurrect old, unsupported versions for this, although I doubt anyone will find time for such small fry even in newest version. Thanks for clarification.
